apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubetemplater
  name: kubetemplater-controller-manager
  namespace: kubetemplater-system
